services:
  db:
    image: postgres:16
    container_name: postgres-db-local
    restart: always
    environment:
      - POSTGRES_DB=crud-security
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=C0nnect123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crud-security
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: C0nnect123

volumes:
  postgres_data: